### ISSUE TITLE
Update for Play Framework 2.6

### ISSUE THREAD

**Issue by AlNedorezov** [remithieblin/play-spring-loader#5]
Nice project.
Any chance of it being updated to work with 2.6?

At the moment for 2.6 app I am getting the following internal server error, for (GET) [/]:

```
NoSuchMethodError: play.api.Environment$.simple$default$2()Lscala/Enumeration$Value;
No source available, here is the exception stack trace:
->java.lang.NoSuchMethodError: play.api.Environment$.simple$default$2()Lscala/Enumeration$Value;
     com.actimust.play.spring.SpringApplicationBuilder.<init>(SpringApplicationBuilder.scala:26)
     com.actimust.play.spring.SpringApplicationLoader.<init>(SpringApplicationLoader.scala:16)
```

**Comment by gmethvin** [comment]
Fixed by #6
